library(msa)
library(Biostrings)
library(seqinr)
library(tidyr)
library(dplyr)
readDNAStringSet("/Users/MariaGarcia/Downloads/sequence-4.fasta") 
seq1 <- readDNAStringSet("/Users/MariaGarcia/Downloads/sequence.fasta")
seq2 <- readDNAStringSet("/Users/MariaGarcia/Downloads/sequence-2.fasta")
seq3 <- readDNAStringSet("/Users/MariaGarcia/Downloads/sequence-3.fasta")
seq4 <- readDNAStringSet("/Users/MariaGarcia/Downloads/sequence-4.fasta")
seq5 <- readDNAStringSet("/Users/MariaGarcia/Downloads/sequence-5.fasta")
seqs <- c(seq1,seq2,seq3,seq4,seq5)
seqs
names(sequences) <- c("S77384.1 cytochrome","FN431808.1 Squatina africana","FN431807.1 Squatina africana","FN431806.1 Squatina africana","FN431805.1 Squatina africana")
SqAfr <-msa(sequences)
nchar(SqAfr)
print(seqs, show="complete")
alphabetFrequency(SqAfr)
alFreq(SqAfr)
??Clustal
sum(alFreq[,"C"]) + sum(alFreq[,"G"]) 
sum(alFreq[,"A"]) + sum(alFreq[,"T"])
GC / (GC + AT )
seqinr::GC(seq_1.seqinr$FN431808.1)
SqAfr <- msaConvert(SqAfr, type="seqinr::alignment")
d <- dist.alignment(SqAfr, "identity")
d
100 - (round(as.matrix(d)[, "S77384.1 cytochrome", drop=FALSE], digits = 2) * 100)
seq_1_A <- Biostrings::translate(seq1)
print(seq_1_AA)
SqAfr <- msaConvert(SqAfr, type="phangorn::phyDat")
rite.phyDat(SqAfr, "sequence.fasta", format = "fasta")
?msa
SqAfr_phyDat <- msaConvert(SqAfr, type="phangorn::phyDat")
write.phyDat(SqAfr_phyDat, format = "fasta")
