library(msa)
library(Biostrings)
library(seqinr)
library(tidyr)
library(dplyr)
readDNAStringSet("/Users/MariaGarcia/Downloads/sequence-4.fasta") 
seq1 <- readDNAStringSet("/Users/MariaGarcia/Downloads/sequence.fasta")
seq2 <- readDNAStringSet("/Users/MariaGarcia/Downloads/sequence-2.fasta")
seq3 <- readDNAStringSet("/Users/MariaGarcia/Downloads/sequence-3.fasta")
seq4 <- readDNAStringSet("/Users/MariaGarcia/Downloads/sequence-4.fasta")
seq5 <- readDNAStringSet("/Users/MariaGarcia/Downloads/sequence-5.fasta")
seqs <- c(seq1,seq2,seq3,seq4,seq5)
seqs
names(seqs) <- c("S77384.1 cytochrome","FN431808.1 Squatina africana","FN431807.1 Squatina africana","FN431806.1 Squatina africana","FN431805.1 Squatina africana")
SqAfr <-msa(seqs)
nchar(SqAfr)
print(SqAfr, show="complete")
alphabetFrequency(SqAfr)
sum(alFreq[,"C"]) + sum(alFreq[,"G"]) 
sum(alFreq[,"A"]) + sum(alFreq[,"T"])
GC / (GC + AT )
seq1.seqinr <- seqinr::read.fasta("/Users/MariaGarcia/Downloads/sequence.fasta")
seqinr::GC(seq1.seqinr$S77384.1 )
SqAfr2 <- msaConvert(SqAfr, type="seqinr::alignment")
dist.alignment(SqAfr2, "identity")
100 - (round(as.matrix(d)[, "S77384.1 cytochrome", drop=FALSE], digits = 2) * 100)
seq1_A <- Biostrings::translate(seq1)
print(seq_1_A)
write.fasta(sequences = seq_1_A , names = seq_1_A, file.out = "seq_1_A")
